stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: GoHelloWorld
- name: publish
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
