stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: go-hello-world
      pushRemote: true
      registry: 127.0.0.1:34032
- name: publish
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
