stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: go-hello-world
      registry: index.docker.io
- name: publish
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
  when:
    branch: {}
timeout: 60
